server:
  port: 8888

spring:
  profiles: dev
  security:
    jwt:
      secret: jwt_secret
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mariadb://115.91.73.66:13306/tdb?characterEncoding=UTF-8&ServerTimezone=UTC
    username: root
    password: Laonpp00..L
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

logging:
  pattern:
    file: /Users/stanjoo/Documents/own/spring_starter/logs.%d{yyyy-MM-dd}.log
  file:
    name: /Users/stanjoo/Documents/own/spring_starter/logs.log